### ISSUE TITLE
Subscription vs old news

### ISSUE THREAD

**Issue by tigelane** [datacenter/acitoolkit#129]
I've been looking at event subscription and running the sample code displays events that have happened in the past (all of them, every time the application is run).  Is there a way to limit this to new events that happen after the subscription happens?

An example output:
('Tenant', 'Place-Holder', 'has been created or modified.')
('Tenant', 'common', 'has been created or modified.')
('Tenant', 'Zynga', 'has been created or modified.')
('Tenant', 'partner1', 'has been created or modified.')
('Tenant', 'infra', 'has been created or modified.')
('Tenant', 'Examples-1', 'has been created or modified.')
('Tenant', 'MPLS-OSP', 'has been created or modified.')

**Comment by michsmit99** [comment]
Which sample code are you running ?

**Comment by tigelane** [comment]
acitoolkit/samples/aci-subscribe-tenants.py

Even when I run my own code it seems like when you subscribe it gives you every event that's ever happened to the object that you subscribe too (I have only looked at Tenant and Application Profile so far).  It also doesn't seem to have a time/date stamp or anything else to key on to drop all of the old ones (maybe I'm wrong, my code skills are not that great.  

Here is my sample code where I just wait 15 seconds to start dealing with the events.  That's plenty of time for them to clear out:  https://github.com/tigelane/cisco_aci-scripts/blob/master/aci-to-twitter.py

PS, try not to laugh at my code if you look.  :laughing:

**Comment by michsmit99** [comment]
By default, the APIC will return all of the currently existing objects for the subscription request. The toolkit queues these up as events.  I just checked in the ability to request only new events (commit 6eacbee87f818ae34ac12d0b4731cbed2b435b86) so the toolkit will not queue the initial set of objects but will queue all events after the initial subscription. The commit adds a new parameter called `only_new`.  The default has `only_new` set to `False` so that it retains the current behavior.  To only get new events in your example, you would use it as follows:
```
aci.Tenant.subscribe(session, only_new=True)
```
