### ISSUE TITLE
Can't unlink contracts from epg

### ISSUE THREAD

**Issue by iparfilov** [datacenter/acitoolkit#183]
Wrote a test, describing the situation. After execution it contracts are still consuming\providing. Consuming and providing works fine. But don't consume/provide does not work as I expected. Please, help
APIC version is 1.2(2h).

import acitoolkit.acitoolkit as aci
session = aci.Session("https://10.7.16.1", "admin", "P@ssw0rd")
resp = session.login(10)
if not resp.ok:
    print('%% Could not login to APIC')

tenant = aci.Tenant("Test-V")
app = aci.AppProfile("ndc-app-profile", tenant)
epg1 = aci.EPG("test-net-1", app)
epg2 = aci.EPG("test-net-2", app)
contract = aci.Contract("666", tenant)
epg2.provide(contract)
epg1.consume(contract)
#Push the tenant to the APIC
resp = session.push_to_apic(tenant.get_url(),
                            tenant.get_json())
if not resp.ok:
    print('%% Error: Could not push configuration to APIC')

session.close()

session = aci.Session("https://10.7.16.1", "admin", "P@ssw0rd")
resp = session.login(10)
if not resp.ok:
    print('%% Could not login to APIC')

tenant = aci.Tenant("Test-V")
app = aci.AppProfile("ndc-app-profile", tenant)
epg1 = aci.EPG("test-net-1", app)
epg2 = aci.EPG("test-net-2", app)
contract = aci.Contract("666", tenant)

epg1.dont_consume(contract)
epg2.dont_provide(contract)
#Push the tenant to the APIC
resp = session.push_to_apic(tenant.get_url(),
                            tenant.get_json())
if not resp.ok:
    print('%% Error: Could not push configuration to APIC')

**Comment by richardstrnad** [comment]
Hi Ivan,

Have a look at #117 , you have to extract the objects from the APIC through .get_deep().
If needed i can provide you an example script.

Regards
Richy

**Comment by iparfilov** [comment]
@richardstrnad thanks . I have tried get_deep(), but I dont want delete objects. I want only delete link to provided/consumed contract, not delete object.

**Comment by michsmit99** [comment]
Hi Ivan,
dont_consume and dont_provide currently only mark the provide/consume relation as deleted.  If there is no relation, it will not be marked as deleted. In your code using the second tenant, the toolkit is not aware of the relation between the EPG and the contract so it will not mark the relation as deleted since it thinks it is already gone.  This is why performing get_deep() as Richy suggests would work i.e. get_deep() and call dont_consume() since the get_deep() allows the toolkit to know that the consume/provide relation exists.  Another option is to tell the toolkit that the relationship exists such as the following code:

tenant = aci.Tenant("Test-V")
app = aci.AppProfile("ndc-app-profile", tenant)
epg1 = aci.EPG("test-net-1", app)
epg2 = aci.EPG("test-net-2", app)
contract = aci.Contract("666", tenant)
**epg1.consume(contract)**
epg1.dont_consume(contract)
**epg2.provide(contract)**
epg2.dont_provide(contract)
#Push the tenant to the APIC
resp = session.push_to_apic(tenant.get_url(),
tenant.get_json())

Perhaps we should change the toolkit code so that dont_consume a contract will push relation deletion even if the toolkit thinks the relation doesn't exist.

**Comment by iparfilov** [comment]
@richardstrnad  @michsmit99 Thanks a lot! Now it is clear.
